## Translations

This an affine transform that simply shifts the position of an image. (left or right).

We use cv2.warpAffine to implement these transformations.


In [2]:
import cv2
import numpy as np


image = cv2.imread('images/input.jpg')

# Store height and width of the image
height, width = image.shape[:2]

# Shift it by quarter of the height and width
quarter_height, quarter_width = height/4, width/4


# T is our translation matrix
T = np.float32([[1, 0, quarter_width], [0, 1,quarter_height]])

#  warpAffine to transform the image using the matrix, T
img_translation = cv2.warpAffine(image, T, (width, height))
cv2.imshow("First",image)
cv2.imshow('Translation', img_translation)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:

print(T)

[[  1.     0.   242.  ]
 [  0.     1.   149.25]]


## Rotations

cv2.getRotationMatrix2D(rotation_center_x, rotation_center_y, angle of rotation, scale)


In [5]:
image = cv2.imread('images/input.jpg')
height, width = image.shape[:2]

# Divide by 2 to rototate the image around its centre
rotation_matrix = cv2.getRotationMatrix2D((width/2, height/2), 90, .5)

# the rotation matrix and  final width and height
rotated_image = cv2.warpAffine(image, rotation_matrix, (width, height))

cv2.imshow('Rotated Image', rotated_image)
cv2.waitKey()
cv2.destroyAllWindows()

### black space surrounding the image.
By simple rotations that uses the cv2.transpose function

In [ ]:
1 2 
3 4 ==== 1 3 5
5 6 ==== 2 4 6

In [7]:
#Other Option to Rotate
img = cv2.imread('images/input.jpg')

rotated_image = cv2.transpose(img)

cv2.imshow('Rotated Image - Method 2', rotated_image)
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
# Let's now to a horizontal flip.
flipped = cv2.flip(image, 1)
cv2.imshow('Original', image) 
cv2.imshow('Horizontal Flip', flipped) 
cv2.waitKey()
cv2.destroyAllWindows()

## Scaling, Re-sizing, Interpolations and Cropping


Re-sizing by cv2.resize function, it's arguments are:

cv2.resize(image, dsize(output image size), x scale, y scale, interpolation)
- if dsize is None the output image is calculated as a function of scaling

#### List of Interpolation Methods:
- cv2.INTER_AREA - Good for shrinking or down sampling
- cv2.INTER_NEAREST - Fastest
- cv2.INTER_LINEAR - Good for zooming or up sampling (default)
- cv2.INTER_CUBIC - Better
- cv2.INTER_LANCZOS4 - Best

In [9]:
import cv2
import numpy as np

image = cv2.imread('images/oxford.jpg')

# If no interpolation is specified cv.INTER_LINEAR is used as default
# Make  image 3/4 of it's original size
image_scaled = cv2.resize(image, None, fx=0.75, fy=0.75)
cv2.imshow('Scaling - Linear Interpolation', image_scaled) 
cv2.waitKey()

# Double the size of  image
img_scaled = cv2.resize(image, None, fx=2, fy=2, interpolation = cv2.INTER_CUBIC)
cv2.imshow('Scaling - Cubic Interpolation', img_scaled)
cv2.waitKey()

#Double the size of  image
img_scaled = cv2.resize(image, None, fx=2, fy=2, interpolation = cv2.INTER_NEAREST)
cv2.imshow('Scaling - Inter Nearest', img_scaled)
cv2.waitKey()

# Skew the re-sizing by setting exact dimensions
img_scaled = cv2.resize(image, (900, 400), interpolation = cv2.INTER_AREA)
cv2.imshow('Scaling - Skewed Size', img_scaled) 
cv2.waitKey()

cv2.destroyAllWindows()

## Image Pyramids

Useful when scaling images in object detection.

In [10]:
smaller = cv2.pyrDown(image)
larger = cv2.pyrUp(smaller)

cv2.imshow('Original', image )

cv2.imshow('Smaller ', smaller )
cv2.imshow('Larger ', larger )
cv2.waitKey(0)
cv2.destroyAllWindows()

## Cropping

In [11]:
image = cv2.imread('images/input.jpg')

height, width = image.shape[:2]

# pixel coordiantes (top  left of cropping rectangle)
# using 0.25 to get the x,y position that is 1/4 down from the top left (0,0)
start_row, start_col = int(height * .25), int(width * .25)

# ending pixel coordinates (bottom right)
end_row, end_col = int(height * .75), int(width * .75)

#indexing to crop out the rectangle we desire
cropped = image[start_row:end_row , start_col:end_col]

cv2.imshow("Original Image", image)
cv2.waitKey(0) 

# (in-place operation)
copy = image.copy()
cv2.rectangle(copy, (start_col,start_row), (end_col,end_row), (0,255,255), 10)
cv2.imshow("Area we are cropping", copy)
cv2.waitKey(0) 

cv2.imshow("Cropped Image", cropped) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

## Arithmetic Operations

In [12]:
M = np.ones(image.shape, dtype = "uint8") * 100 
print(M)

# We use this to add this matrix M, to our image
# Increase in brightness
added = cv2.add(image, M)
cv2.imshow("Added", added)

# Now if we just added it, look what happens
added2 = image + M 
cv2.imshow("Added 2", added2)

# Subtract
# decrease in brightness
subtracted = cv2.subtract(image, M)
cv2.imshow("Subtracted", subtracted)

added3 = image - M 
cv2.imshow("Subtracted 2", added3)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 ...

 [[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]
  [100 100 100]
  ...
  [100 100 100]
  [100 100 100]
  [100 100 100]]]


## Bitwise Operations and Masking

In [13]:

# Making a sqare
square = np.zeros((300, 300), np.uint8)
cv2.rectangle(square, (50, 50), (250, 250), 255, -2)
cv2.imshow("Square", square)
cv2.waitKey(0)

# Making a ellipse
ellipse = np.zeros((300, 300), np.uint8)
cv2.ellipse(ellipse, (150, 150), (150, 150), 30, 0, 180, 255, -1)
cv2.imshow("Ellipse", ellipse)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [ ]:
# Shows only where they intersect
And = cv2.bitwise_and(square, ellipse)
cv2.imshow("AND", And)
cv2.waitKey(0)

# Shows where either square or ellipse is 
bitwiseOr = cv2.bitwise_or(square, ellipse)
cv2.imshow("OR", bitwiseOr)
cv2.waitKey(0) 

# Shows where either exist by itself
bitwiseXor = cv2.bitwise_xor(square, ellipse)
cv2.imshow("XOR", bitwiseXor)
cv2.waitKey(0)

# Shows everything that isn't part of the square
bitwiseNot_sq = cv2.bitwise_not(square)
cv2.imshow("NOT - square", bitwiseNot_sq)
cv2.waitKey(0)

###  last operation inverts the image totally

cv2.destroyAllWindows()